apiVersion: apps/v1
kind: Deployment
metadata:
  name: universalresolver-didcomm
  namespace: uni-resolver
  labels:
    app: uni-resolver
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: universalresolver-didcomm
  template:
    metadata:
      labels:
        app: universalresolver-didcomm
    spec:
      containers:
      - name: universalresolver-didcomm
        image: universalresolver/universalresolver-didcomm
        imagePullPolicy: Always
        ports:
        - containerPort: 8180
        - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: universalresolver-didcomm
spec:
  type: NodePort
  selector:
    app: universalresolver-didcomm
  ports:
    - protocol: TCP
      port: 8180
      targetPort: 8180
    - protocol: TCP
      port: 8181
      targetPort: 8181
